#!/bin/bash
echo "Watching $1"
ls -lh $1

mkindex () {
    export IMAGE_TO_SERVE=$1
    envsubst < /watcher/index.tpl > /srv/index.html
}

inotifywait -m $1 -e close_write -e moved_to |
  while read path action file; do
    echo "The file '$file' appeared in directory '$path' via '$action'"
    mv $path$file /srv/images/
    mkindex $file
  done
